### ISSUE TITLE
Allow for defining the fraction of the vdisksets as a percentage 

### ISSUE THREAD

**Issue by dannyk96** [IBM/SpectrumScale_GNR_CAPACITY_ESTIMATOR#1]
Moast sites create one of more filesystems of say up to 98% of the physical.

Please can the tool have an extra parameter to reflect --set-size as a percentage?

eg on one of my ECE clusters I have --set-size of 98%
On the other I have 2 filesystems : one of 75%, the other of 20%

It would be great if this estimator can reflect this - so I can run it on my cluster and check that the actual usable capacicity (df -H)
closely matchs what the tool predicts.

**Comment by bolinches** [comment]
Hi Daniel. Nice to "see" you again. 

I will add the % but not the ability to pass multiple FS, you would need to run once per FS and % sum 100% after all runs

**Comment by dannyk96** [comment]
Great!
No need for multiple filesystem support - just the ability to set say a "30%" or a "95%" value so reflect what actually happens when creating a vidskset and a fs.

**Comment by bolinches** [comment]
Hi

Now that got some time ....

https://github.com/IBM/SpectrumScale_ECE_CAPACITY_ESTIMATOR/commit/c9676850bfe6654372f3d4934cd61519adc1a6e5

should address your request ...
